name: build-lexilla

on:
  push:
    paths:
      - lexilla
      - .github/workflows/build-lexilla.yml

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Xcode Select
        run: |
          # find latest Xcode
          XCODE_PATH=$(find /Applications -maxdepth 1 -type d -name 'Xcode*' | sort -r | head -n 1)
          echo "Xcode Path: $XCODE_PATH"
          # set Xcode version
          sudo xcode-select -switch "$XCODE_PATH"
          echo "Xcode Version: $(xcodebuild -version)"
          # make build directory
          mkdir build

      - name: Build Lexilla
        working-directory: build
        run: |
          # build target 'liblexilla.dylib' (staticlib actually)
          xcodebuild -project ../lexilla/src/Lexilla/Lexilla.xcodeproj archive -scheme lexilla -configuration Release -destination "generic/platform=macOS" -archivePath "archives/lexilla" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES DEVELOPMENT_TEAM="" MACH_O_TYPE=staticlib
          # copy to 'liblexilla.a'
          find . -name 'liblexilla.dylib' -exec mv {} ./liblexilla.a \;
          # make xcframework
          cp -r ../lexilla/include ./include
          xcodebuild -create-xcframework -library liblexilla.a -headers include -output Lexilla.xcframework

      - name: Tar xcframework
        working-directory: build
        run: |
          mkdir dist
          tar --zstd -cvf dist/Lexilla.xcframework.tar.zst Lexilla.xcframework

      - name: Upload xcframework
        uses: shallwefootball/s3-upload-action@v1.3.3
        with:
          endpoint: ${{ secrets.AWS_ENDPOINT }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source_dir: build/dist
          destination_dir: lexilla/$GITHUB_SHA
