name: hg-mirror

on:
  schedule:
    - cron: "45 12 * * *"
  push:
    paths:
      - .github/workflows/hg-mirror.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - uses: mozillazg/mirror-hg-repo@v2
        with:
          source-hg-repo-url: http://hg.code.sf.net/p/scintilla/code
          destination-git-repo-owner: zengxs
          destination-git-repo-name: scintilla-code
          destination-git-personal-token: "${{ secrets.PERSONAL_GIT_TOKEN }}"
